import requests

session = requests.Session()

rawBody = "{\r\n   \"workflow_type_id\": 70,\r\n   \"data\" : [\r\n        \r\n        {\r\n            \"value\": \"Principal Reference\",\r\n            \"name\": \"principal_reference\"\r\n        },\r\n        {\r\n            \"value\": \"2018-01-01\",\r\n            \"name\": \"accident_date\"\r\n        },\r\n        {\r\n            \"value\": \"01513429961\",\r\n            \"name\": \"inspection_contact_phone\"\r\n        },\r\n        {\r\n            \"value\": \"0777777777\",\r\n            \"name\": \"inspection_contact_mobile\"\r\n        },\r\n        {\r\n            \"value\": \"Ring 2hrs before arrival\",\r\n            \"name\": \"agent_special_instructions\"\r\n        },\r\n        {\r\n            \"value\": \"Important Client\",\r\n            \"name\": \"principal_comments\"\r\n        },\r\n        {\r\n            \"value\": \"Rear\",\r\n            \"name\": \"area_of_damage_to_vehicle_reported\"\r\n        },\r\n        {\r\n            \"value\": \"Car has been in previouse accident on 17th may 2017 and was repaired\",\r\n            \"name\": \"agent_important_special_instructions\"\r\n        },\r\n        {\r\n            \"value\": \"MD accident management\",\r\n            \"name\": \"file_referrer\"\r\n        },\r\n        {\r\n            \"value\": \"Mr\",\r\n            \"name\": \"client_salutation\"\r\n        },\r\n        {\r\n            \"value\": \"Lee\",\r\n            \"name\": \"client_first_value\"\r\n        },\r\n        {\r\n            \"value\": \"Baty\",\r\n            \"name\": \"client_second_value\"\r\n        },\r\n        {\r\n            \"value\": \"CH607RJ\",\r\n            \"name\": \"client_postcode\"\r\n        },\r\n        {\r\n            \"value\": \"lee.baty@laird-assessors.com\",\r\n            \"name\": \"client_email_address\"\r\n        },\r\n        {\r\n            \"value\": \"01513429961\",\r\n            \"name\": \"client_daytime_phone\"\r\n        },\r\n        {\r\n            \"value\": \"01513429961\",\r\n            \"name\": \"client_evening_phone\"\r\n        },\r\n        {\r\n            \"value\": \"0777777777\",\r\n            \"name\": \"client_mobile\"\r\n        },\r\n        {\r\n            \"value\": \"VIP\",\r\n            \"name\": \"client_phone_notes\"\r\n        },\r\n        {\r\n            \"value\": \"Lee Baty\",\r\n            \"name\": \"contact_for_inspection\"\r\n        },\r\n        {\r\n            \"value\": \"Laird Assesors 188 - 200 Whitfield Buildings,heswall,wirral\",\r\n            \"name\": \"inspection_address\"\r\n        },\r\n        {\r\n            \"value\": \"W705ACW\",\r\n            \"name\": \"vehicle_registration\"\r\n        },\r\n        {\r\n            \"value\": \"In Use\",\r\n            \"name\": \"on_site_in_use\"\r\n        }\r\n     \r\n\r\n         \r\n\r\n\r\n\x09]\r\n}"
headers = {"User-Agent":"API DEMO","Connection":"close","Accept-Encoding":"gzip, deflate","Accept":"*/*","Content-Type":"application/json"}
response = session.post("https://test2-lairdassessors.swiftcase.co.uk/api/v2/YOURAPIKEY/task.json", data=rawBody, headers=headers)

print("Status code:   %i" % response.status_code)
print("Response body: %s" % response.content)

